### ISSUE TITLE
Predicting Entire path

### ISSUE THREAD

**Issue by Bouncer51** [Priyanshiguptaaa/Flipkart_Product_Categorization#2]
https://arxiv.org/pdf/1812.05774v1.pdf has shown that we could predict the entire product tree. Have you tried that instead of predicting the primary category. if we want to do entire tree what potential changes could be done in present implementation.

Could you also tell how much time did the training took and the configurations of the training system?

Thanks

**Comment by Priyanshiguptaaa** [comment]
Yes, we can predict the whole tree, but due to computational constraints, I first worked on classifying based on the primary category.  For translating into the entire tree, I suggest, instead of extracting the primary category, you can use the category structure that is given initially, i.e. ["Clothing >> Women's Clothing >> Lingerie, Sleep & Swimwear >> Shorts >> Alisha Shorts >> Alisha Solid Women's Cycling Shorts"] as the second language instead of ["Clothing"], and clean up the dataset according to this norm. You'll have to make modifications in the **Class Lang** accordingly and make sure that it is able to identify >> as a seperater. 

For training, without Colab GPU, it took 11 hours. With GPU it worked in 45 mins.

Hope this helps!

**Comment by Bouncer51** [comment]
Thank you so much. It helps.
